# curl http://localhost:8080/demo/add -d name=First -d email=someemail@someemailprovider.com
POST http://localhost:8080/demo/add
Content-Type: application/x-www-form-urlencoded

name=First&email=someemail@someemailprovider.com

###

# @no-redirect
GET http://localhost:8080/demo/all
###


#############
GET http://localhost:8080/spotify/getCategories
###
POST http://localhost:8080/spotify/createPlaylist
name:HalloWelt
###
GET http://localhost:8080/api/user-top-songs
Content-Type: application/x-www-form-urlencoded

user-id=11143388735
###

GET http://localhost:8080/album/1

###
GET http://localhost:8080/album/all
